---
# vim: set filetype=yaml.ansible : #

- name: ZSH | Dependencies Debian
  when: ansible_os_family == 'Debian'
  ansible.builtin.apt:
    name:
      - zsh
    state: present
  become: true

- name: ZSH | Dependencies RedHat
  when: ansible_os_family == 'RedHat'
  ansible.builtin.dnf:
    name:
      - zsh
      - tldr
      - fd-find
      - git
      - trash-cli
      - tree
    state: present
  become: true

- name: ZSH | Check if .oh-my-zsh exists
  ansible.builtin.stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Cloning oh-my-zsh
  ansible.builtin.git:
    repo: https://github.com/robbyrussell/oh-my-zsh
    dest: ~/.oh-my-zsh
    version: master
  when:
    - not stat_oh_my_zsh_result.stat.exists
    - ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Check oh-my-zsh folder owner
  ansible.builtin.file:
    path: '~/.oh-my-zsh'
    state: directory
    owner: '{{ host_user }}'
    group: '{{ host_user }}'
    recurse: true
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Cloning zsh-autosuggestions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
    version: master
  # when: not stat_oh_my_zsh_result.stat.exists
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Cloning zsh-syntax-highlighting
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting
    dest: ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
    version: master
  # when: not stat_oh_my_zsh_result.stat.exists
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Create zsh maccan theme
  ansible.builtin.copy:
    src: maccan.zsh-theme
    dest: ~/.oh-my-zsh/custom/themes/maccan.zsh-theme
    mode: "0644"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | "Copy .zshrc"
  ansible.builtin.copy:
    src: "zshrc"
    dest: "{{ ansible_user_dir }}/.zshrc"
    mode: "0644"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Set default shell for users
  become: true
  ansible.builtin.user:
    name: '{{ host_user }}'
    shell: /usr/bin/zsh
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: "ZSH | bin folder"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/bin"
    state: directory

- name: ZSH | Copy notetaker script
  ansible.builtin.copy:
    src: "notetaker"
    dest: "{{ ansible_user_dir }}/bin/notetaker"
    mode: "0755"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'

- name: ZSH | Copy netinfo script
  ansible.builtin.copy:
    src: "ip_a_formating.awk"
    dest: "{{ ansible_user_dir }}/bin/ip_a_formating.awk"
    mode: "0755"
  when: ansible_os_family == 'Debian' or ansible_os_family == 'RedHat'
