#!/bin/bash
#
# Settings menu (Alt+Shift+S): rofi menus that change Hyprland settings live.
#
# Changes are applied with `hyprctl eval` and, once confirmed, stored in
# ~/.local/state/hypr/monitors.json. From that, settings.lua is generated,
# which hyprland.lua loads last. Both live outside the Ansible-managed config,
# so a deploy does not reset them.
#
# Sections: Display (scale, resolution, rotation).

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/hypr"
MONITORS_STATE="$STATE_DIR/monitors.json"
SETTINGS_LUA="$STATE_DIR/settings.lua"
ROFI_CONFIG="$HOME/.config/rofi/config-singlecol.rasi"
CONFIRM_SECONDS=15

# Scales offered in the menu; each is snapped to one Hyprland accepts
SCALES=(1 1.25 1.5 1.75 2 2.5 3)

mkdir -p "$STATE_DIR"
[ -f "$MONITORS_STATE" ] || echo '{}' > "$MONITORS_STATE"

# rofi_menu <prompt> <active row|-1> <rows...>  ->  prints the chosen row index
rofi_menu() {
    local prompt="$1" active="$2"
    shift 2
    local lines=$(( $# < 12 ? $# : 12 ))
    local args=(-dmenu -i -format i -p "$prompt" -config "$ROFI_CONFIG" -l "$lines")
    if [ "$active" -ge 0 ]; then
        args+=(-a "$active" -selected-row "$active")
    fi
    printf '%s\n' "$@" | rofi "${args[@]}"
}

# row <label> <value>: aligned two-column menu row
row() {
    printf '%-12s %s' "$1" "$2"
}

# ----------------------------------------------------------------------------
# Display
# ----------------------------------------------------------------------------

monitor_json() {
    hyprctl -j monitors | jq -c --arg name "$1" '.[] | select(.name == $name)'
}

transform_name() {
    case "$1" in
        0) echo "Normal" ;;
        1) echo "90°" ;;
        2) echo "180°" ;;
        3) echo "270°" ;;
        *) echo "$1" ;;
    esac
}

# Hyprland only accepts scales that divide the mode into whole logical pixels
# (in 1/120 steps). Round up to the nearest such scale.
clean_scale() {
    awk -v scale="$1" -v width="$2" -v height="$3" '
        function gcd(a, b, t) { while (b) { t = a % b; a = b; b = t } return a }
        BEGIN {
            g = gcd(width * 120, height * 120)
            k = int(scale * 120 + 0.5)
            if (k > g) k = g
            while (g % k != 0) k++
            printf "%g\n", k / 120
        }'
}

lua_monitor() {
    # lua_monitor <desc> <mode> <scale> <transform>
    printf 'hl.monitor({ output = %s, mode = "%s", position = "auto", scale = %s, transform = %s })' \
        "$(jq -n --arg d "desc:$1" '$d')" "$2" "$3" "$4"
}

# apply_monitor <desc> <mode> <scale> <transform>
# hyprctl eval returns before the monitor is reconfigured (it can lag while a
# rofi window closes), so wait until Hyprland reports the new values;
# otherwise the menu shown next reads the old ones.
apply_monitor() {
    local desc="$1" mode="$2" scale="$3" transform="$4" i
    hyprctl eval "$(lua_monitor "$@")" > /dev/null
    for i in $(seq 1 30); do
        hyprctl -j monitors | jq -e --arg d "$desc" --arg res "${mode%@*}" \
            --argjson s "$scale" --argjson t "$transform" \
            '.[] | select(.description == $d)
                 | select("\(.width)x\(.height)" == $res and ((.scale - $s) | fabs) < 0.001 and .transform == $t)' \
            > /dev/null && return 0
        sleep 0.1
    done
}

write_settings_lua() {
    {
        echo "-- Generated by ~/.config/hypr/scripts/settings.sh (Alt+Shift+S)."
        echo "-- Do not edit by hand; use the settings menu or delete this file."
        jq -r 'to_entries[] | [.key, .value.mode, (.value.scale | tostring), (.value.transform | tostring)] | @tsv' \
            "$MONITORS_STATE" |
            while IFS=$'\t' read -r desc mode scale transform; do
                lua_monitor "$desc" "$mode" "$scale" "$transform"
                echo
            done
    } > "$SETTINGS_LUA"
}

save_monitor() {
    # save_monitor <desc> <mode> <scale> <transform>
    local tmp
    tmp=$(mktemp)
    jq --arg d "$1" --arg m "$2" --argjson s "$3" --argjson t "$4" \
        '.[$d] = { mode: $m, scale: $s, transform: $t }' "$MONITORS_STATE" > "$tmp" &&
        mv "$tmp" "$MONITORS_STATE"
    write_settings_lua
}

forget_monitor() {
    local tmp
    tmp=$(mktemp)
    jq --arg d "$1" 'del(.[$d])' "$MONITORS_STATE" > "$tmp" && mv "$tmp" "$MONITORS_STATE"
    write_settings_lua
}

# Ask to keep the new settings; anything but "Keep" within the timeout reverts.
# "Revert" comes first so a blind Enter on an unreadable screen undoes the change.
confirm_change() {
    local answer
    answer=$(printf '%s\n' "Revert" "Keep" |
        timeout "$CONFIRM_SECONDS" rofi -dmenu -i -l 2 -config "$ROFI_CONFIG" \
            -p "Keep display settings?" -mesg "Reverting in $CONFIRM_SECONDS seconds")
    [ "$answer" = "Keep" ]
}

# change_monitor <name> <mode> <scale> <transform>
change_monitor() {
    local name="$1" mode="$2" scale="$3" transform="$4"
    local m desc old_mode old_scale old_transform
    m=$(monitor_json "$name")
    desc=$(jq -r '.description' <<< "$m")
    old_mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    old_scale=$(jq -r '.scale' <<< "$m")
    old_transform=$(jq -r '.transform' <<< "$m")

    apply_monitor "$desc" "$mode" "$scale" "$transform"
    if confirm_change; then
        save_monitor "$desc" "$mode" "$scale" "$transform"
    else
        apply_monitor "$desc" "$old_mode" "$old_scale" "$old_transform"
    fi
}

choose_scale() {
    local name="$1" m width height mode current transform
    m=$(monitor_json "$name")
    width=$(jq -r '.width' <<< "$m")
    height=$(jq -r '.height' <<< "$m")
    mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    current=$(jq -r '.scale' <<< "$m")
    transform=$(jq -r '.transform' <<< "$m")

    local values=() rows=() active=-1 s seen=" "
    for s in "${SCALES[@]}"; do
        s=$(clean_scale "$s" "$width" "$height")
        [[ $seen == *" $s "* ]] && continue
        seen+="$s "
        values+=("$s")
        rows+=("$(row "$s" "$(awk -v w="$width" -v h="$height" -v s="$s" \
            'BEGIN { printf "looks like %dx%d", w / s + 0.5, h / s + 0.5 }')")")
        awk -v a="$s" -v b="$current" 'BEGIN { exit !(a == b) }' && active=$((${#values[@]} - 1))
    done

    local i
    i=$(rofi_menu "Scale" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    change_monitor "$name" "$mode" "${values[$i]}" "$transform"
}

choose_resolution() {
    local name="$1" m current scale transform
    m=$(monitor_json "$name")
    current=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    scale=$(jq -r '.scale' <<< "$m")
    transform=$(jq -r '.transform' <<< "$m")

    local modes=() rows=() active=-1 mode res hz
    mapfile -t modes < <(jq -r '.availableModes[] | sub("Hz$"; "")' <<< "$m" | awk '!seen[$0]++')
    for mode in "${modes[@]}"; do
        res=${mode%@*}
        hz=${mode#*@}
        rows+=("$(row "$res" "$hz Hz")")
        awk -v a="$hz" -v b="${current#*@}" 'BEGIN { exit !(a + 0 == b + 0) }' &&
            [ "$res" = "${current%@*}" ] && [ "$active" -lt 0 ] && active=$((${#rows[@]} - 1))
    done

    local i
    i=$(rofi_menu "Resolution" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    # Keep the scale valid for the new resolution
    res=${modes[$i]%@*}
    scale=$(clean_scale "$scale" "${res%x*}" "${res#*x}")
    change_monitor "$name" "${modes[$i]}" "$scale" "$transform"
}

choose_rotation() {
    local name="$1" m mode scale current
    m=$(monitor_json "$name")
    mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    scale=$(jq -r '.scale' <<< "$m")
    current=$(jq -r '.transform' <<< "$m")

    local i
    i=$(rofi_menu "Rotation" "$current" "Normal" "90°" "180°" "270°") || return
    [ "$i" = "$current" ] && return
    change_monitor "$name" "$mode" "$scale" "$i"
}

reset_monitor() {
    local name="$1" m desc
    m=$(monitor_json "$name")
    desc=$(jq -r '.description' <<< "$m")
    local i
    i=$(rofi_menu "Reset $name to defaults?" -1 "Reset" "Cancel") || return
    [ "$i" = "0" ] || return
    forget_monitor "$desc"
    hyprctl eval "hl.monitor({ output = $(jq -n --arg d "desc:$desc" '$d'), mode = \"preferred\", position = \"auto\", scale = 1 })" > /dev/null
}

display_menu() {
    local name="$1" m i
    while true; do
        m=$(monitor_json "$name")
        [ -n "$m" ] || return
        i=$(rofi_menu "Display $name" -1 \
            "$(row "Scale" "$(jq -r '.scale' <<< "$m")")" \
            "$(row "Resolution" "$(jq -r '"\(.width)x\(.height) @ \(.refreshRate * 100 | round / 100) Hz"' <<< "$m")")" \
            "$(row "Rotation" "$(transform_name "$(jq -r '.transform' <<< "$m")")")" \
            "Reset to defaults") || return
        case "$i" in
            0) choose_scale "$name" ;;
            1) choose_resolution "$name" ;;
            2) choose_rotation "$name" ;;
            3) reset_monitor "$name" ;;
        esac
    done
}

choose_display() {
    local names=() rows=()
    mapfile -t names < <(hyprctl -j monitors | jq -r '.[].name')
    if [ "${#names[@]}" -eq 1 ]; then
        display_menu "${names[0]}"
        return
    fi
    mapfile -t rows < <(hyprctl -j monitors | jq -r '.[] | "\(.name)  \(.make) \(.model)"')
    local i
    while i=$(rofi_menu "Display" -1 "${rows[@]}"); do
        display_menu "${names[$i]}"
    done
}

# ----------------------------------------------------------------------------
# Main menu
# ----------------------------------------------------------------------------

main_menu() {
    local i
    while i=$(rofi_menu "Settings" -1 "󰍹  Display"); do
        case "$i" in
            0) choose_display ;;
        esac
    done
}

# Only open the menu when run directly, so the functions can be sourced
[[ ${BASH_SOURCE[0]} == "$0" ]] && main_menu
