#!/bin/bash
#
# Settings menu (Alt+Shift+S): rofi menus that change Hyprland settings live.
#
# Changes are applied with `hyprctl eval` and, once confirmed, stored in
# ~/.local/state/hypr/monitors.json. From that, settings.lua is generated,
# which hyprland.lua loads last. Both live outside the Ansible-managed config,
# so a deploy does not reset them.
#
# Sections: Display (scale, resolution, rotation, adaptive sync, night light),
# Appearance (gaps, borders, rounding, opacity, blur, shadows, animations),
# Power and idle (hypridle timeouts, power profile).

STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/hypr"
MONITORS_STATE="$STATE_DIR/monitors.json"
# Settings that are not per monitor, e.g.
# { "nightlight": 4000, "config": { "general.gaps_in": 8 }, "animations": { ... } }
GLOBAL_STATE="$STATE_DIR/settings.json"
SETTINGS_LUA="$STATE_DIR/settings.lua"
# Generated hypridle config; scripts/hypridle.sh prefers it over the default
IDLE_CONF="$STATE_DIR/hypridle.conf"
ROFI_CONFIG="$HOME/.config/rofi/config-singlecol.rasi"
CONFIRM_SECONDS=15

# Scales offered in the menu; each is snapped to one Hyprland accepts
SCALES=(1 1.25 1.5 1.75 2 2.5 3)

# Night light color temperatures in kelvin; lower is warmer
NIGHTLIGHT_TEMPS=(5500 5000 4500 4000 3500 3000)

mkdir -p "$STATE_DIR"
[ -f "$MONITORS_STATE" ] || echo '{}' > "$MONITORS_STATE"
[ -f "$GLOBAL_STATE" ] || echo '{}' > "$GLOBAL_STATE"

# rofi_menu <prompt> <active row|-1> <rows...>  ->  prints the chosen row index
rofi_menu() {
    local prompt="$1" active="$2"
    shift 2
    local lines=$(( $# < 18 ? $# : 18 ))
    local args=(-dmenu -i -format i -p "$prompt" -config "$ROFI_CONFIG" -l "$lines")
    if [ "$active" -ge 0 ]; then
        args+=(-a "$active" -selected-row "$active")
    fi
    # Rows may contain Pango markup (e.g. color swatches) when this is set
    [ -n "$ROFI_MARKUP" ] && args+=(-markup-rows)
    printf '%s\n' "$@" | rofi "${args[@]}"
}

# show_message <prompt> <text>: one-button info dialog
show_message() {
    echo "OK" | rofi -dmenu -i -l 1 -p "$1" -mesg "$2" -config "$ROFI_CONFIG" > /dev/null
}

# row <label> <value>: aligned two-column menu row
row() {
    printf '%-18s %s' "$1" "$2"
}

# ----------------------------------------------------------------------------
# Display
# ----------------------------------------------------------------------------

monitor_json() {
    hyprctl -j monitors | jq -c --arg name "$1" '.[] | select(.name == $name)'
}

transform_name() {
    case "$1" in
        0) echo "Normal" ;;
        1) echo "90°" ;;
        2) echo "180°" ;;
        3) echo "270°" ;;
        *) echo "$1" ;;
    esac
}

vrr_name() {
    case "$1" in
        0) echo "Off" ;;
        1) echo "On" ;;
        2) echo "Fullscreen only" ;;
        3) echo "Fullscreen games and video" ;;
        *) echo "$1" ;;
    esac
}

# Adaptive sync is stored per monitor; Hyprland only reports whether it is
# active right now, not the chosen mode
saved_vrr() {
    jq -r --arg d "$1" '.[$d].vrr // 0' "$MONITORS_STATE"
}

# Hyprland only accepts scales that divide the mode into whole logical pixels
# (in 1/120 steps). Round up to the nearest such scale.
clean_scale() {
    awk -v scale="$1" -v width="$2" -v height="$3" '
        function gcd(a, b, t) { while (b) { t = a % b; a = b; b = t } return a }
        BEGIN {
            g = gcd(width * 120, height * 120)
            k = int(scale * 120 + 0.5)
            if (k > g) k = g
            while (g % k != 0) k++
            printf "%g\n", k / 120
        }'
}

lua_monitor() {
    # lua_monitor <desc> <mode> <scale> <transform> [vrr]
    printf 'hl.monitor({ output = %s, mode = "%s", position = "auto", scale = %s, transform = %s, vrr = %s })' \
        "$(jq -n --arg d "desc:$1" '$d')" "$2" "$3" "$4" "${5:-0}"
}

# apply_monitor <desc> <mode> <scale> <transform> [vrr]
# hyprctl eval returns before the monitor is reconfigured (it can lag while a
# rofi window closes), so wait until Hyprland reports the new values;
# otherwise the menu shown next reads the old ones.
apply_monitor() {
    local desc="$1" mode="$2" scale="$3" transform="$4" i
    hyprctl eval "$(lua_monitor "$@")" > /dev/null
    for i in $(seq 1 30); do
        hyprctl -j monitors | jq -e --arg d "$desc" --arg res "${mode%@*}" \
            --argjson s "$scale" --argjson t "$transform" \
            '.[] | select(.description == $d)
                 | select("\(.width)x\(.height)" == $res and ((.scale - $s) | fabs) < 0.001 and .transform == $t)' \
            > /dev/null && return 0
        sleep 0.1
    done
}

write_settings_lua() {
    {
        echo "-- Generated by ~/.config/hypr/scripts/settings.sh (Alt+Shift+S)."
        echo "-- Do not edit by hand; use the settings menu or delete this file."
        jq -r 'to_entries[] | [.key, .value.mode, (.value.scale | tostring),
                (.value.transform | tostring), (.value.vrr // 0 | tostring)] | @tsv' \
            "$MONITORS_STATE" |
            while IFS=$'\t' read -r desc mode scale transform vrr; do
                lua_monitor "$desc" "$mode" "$scale" "$transform" "$vrr"
                echo
            done
        # Appearance: flat "section.key" entries become one nested hl.config table
        jq -r '
            def lua: if type == "object"
                then "{ " + ([to_entries[] | "\(.key) = \(.value | lua)"] | join(", ")) + " }"
                elif type == "string" then tojson
                else tostring end;
            (.config // {} | select(length > 0)
                | reduce to_entries[] as $e ({}; setpath($e.key | split("."); $e.value))
                | "hl.config(\(lua))"),
            (.animations // {} | to_entries[]
                | "hl.animation({ leaf = \(.key | tojson), enabled = true, speed = \(.value.speed),"
                  + " bezier = \(.value.bezier | tojson), style = \(.value.style | tojson) })")
        ' "$GLOBAL_STATE"
        local temp
        temp=$(saved_nightlight)
        if [ "$temp" != "0" ]; then
            echo "hl.on(\"hyprland.start\", function() hl.exec_cmd(\"hyprsunset --temperature $temp\") end)"
        fi
    } > "$SETTINGS_LUA"
}

save_monitor() {
    # save_monitor <desc> <mode> <scale> <transform> <vrr>
    local tmp
    tmp=$(mktemp)
    jq --arg d "$1" --arg m "$2" --argjson s "$3" --argjson t "$4" --argjson v "${5:-0}" \
        '.[$d] = { mode: $m, scale: $s, transform: $t, vrr: $v }' "$MONITORS_STATE" > "$tmp" &&
        mv "$tmp" "$MONITORS_STATE"
    write_settings_lua
}

forget_monitor() {
    local tmp
    tmp=$(mktemp)
    jq --arg d "$1" 'del(.[$d])' "$MONITORS_STATE" > "$tmp" && mv "$tmp" "$MONITORS_STATE"
    write_settings_lua
}

# Ask to keep the new settings; anything but "Keep" within the timeout reverts.
# "Revert" comes first so a blind Enter on an unreadable screen undoes the change.
confirm_change() {
    local answer
    answer=$(printf '%s\n' "Revert" "Keep" |
        timeout "$CONFIRM_SECONDS" rofi -dmenu -i -l 2 -config "$ROFI_CONFIG" \
            -p "Keep display settings?" -mesg "Reverting in $CONFIRM_SECONDS seconds")
    [ "$answer" = "Keep" ]
}

# change_monitor <name> <mode> <scale> <transform> [vrr]
change_monitor() {
    local name="$1" mode="$2" scale="$3" transform="$4"
    local m desc old_mode old_scale old_transform old_vrr vrr
    m=$(monitor_json "$name")
    desc=$(jq -r '.description' <<< "$m")
    old_mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    old_scale=$(jq -r '.scale' <<< "$m")
    old_transform=$(jq -r '.transform' <<< "$m")
    old_vrr=$(saved_vrr "$desc")
    vrr="${5:-$old_vrr}"

    apply_monitor "$desc" "$mode" "$scale" "$transform" "$vrr"
    if confirm_change; then
        save_monitor "$desc" "$mode" "$scale" "$transform" "$vrr"
    else
        apply_monitor "$desc" "$old_mode" "$old_scale" "$old_transform" "$old_vrr"
    fi
}

choose_scale() {
    local name="$1" m width height mode current transform
    m=$(monitor_json "$name")
    width=$(jq -r '.width' <<< "$m")
    height=$(jq -r '.height' <<< "$m")
    mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    current=$(jq -r '.scale' <<< "$m")
    transform=$(jq -r '.transform' <<< "$m")

    local values=() rows=() active=-1 s seen=" "
    for s in "${SCALES[@]}"; do
        s=$(clean_scale "$s" "$width" "$height")
        [[ $seen == *" $s "* ]] && continue
        seen+="$s "
        values+=("$s")
        rows+=("$(row "$s" "$(awk -v w="$width" -v h="$height" -v s="$s" \
            'BEGIN { printf "looks like %dx%d", w / s + 0.5, h / s + 0.5 }')")")
        awk -v a="$s" -v b="$current" 'BEGIN { exit !(a == b) }' && active=$((${#values[@]} - 1))
    done

    local i
    i=$(rofi_menu "Scale" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    change_monitor "$name" "$mode" "${values[$i]}" "$transform"
}

choose_resolution() {
    local name="$1" m current scale transform
    m=$(monitor_json "$name")
    current=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    scale=$(jq -r '.scale' <<< "$m")
    transform=$(jq -r '.transform' <<< "$m")

    local modes=() rows=() active=-1 mode res hz
    mapfile -t modes < <(jq -r '.availableModes[] | sub("Hz$"; "")' <<< "$m" | awk '!seen[$0]++')
    for mode in "${modes[@]}"; do
        res=${mode%@*}
        hz=${mode#*@}
        rows+=("$(row "$res" "$hz Hz")")
        awk -v a="$hz" -v b="${current#*@}" 'BEGIN { exit !(a + 0 == b + 0) }' &&
            [ "$res" = "${current%@*}" ] && [ "$active" -lt 0 ] && active=$((${#rows[@]} - 1))
    done

    local i
    i=$(rofi_menu "Resolution" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    # Keep the scale valid for the new resolution
    res=${modes[$i]%@*}
    scale=$(clean_scale "$scale" "${res%x*}" "${res#*x}")
    change_monitor "$name" "${modes[$i]}" "$scale" "$transform"
}

choose_rotation() {
    local name="$1" m mode scale current
    m=$(monitor_json "$name")
    mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    scale=$(jq -r '.scale' <<< "$m")
    current=$(jq -r '.transform' <<< "$m")

    local i
    i=$(rofi_menu "Rotation" "$current" "Normal" "90°" "180°" "270°") || return
    [ "$i" = "$current" ] && return
    change_monitor "$name" "$mode" "$scale" "$i"
}

# Adaptive sync (VRR). Whether a monitor supports it is only known by trying:
# Hyprland refuses to enable it on an incapable monitor and keeps reporting
# vrr = false, so test with "On" first and give up with a message if needed.
choose_vrr() {
    local name="$1" m desc mode scale transform current
    m=$(monitor_json "$name")
    desc=$(jq -r '.description' <<< "$m")
    mode=$(jq -r '"\(.width)x\(.height)@\(.refreshRate * 100 | round / 100)"' <<< "$m")
    scale=$(jq -r '.scale' <<< "$m")
    transform=$(jq -r '.transform' <<< "$m")
    current=$(saved_vrr "$desc")

    local i
    i=$(rofi_menu "Adaptive sync" "$current" \
        "$(vrr_name 0)" "$(vrr_name 1)" "$(vrr_name 2)" "$(vrr_name 3)") || return
    [ "$i" = "$current" ] && return

    if [ "$i" != "0" ]; then
        apply_monitor "$desc" "$mode" "$scale" "$transform" 1
        sleep 0.5
        if [ "$(monitor_json "$name" | jq -r '.vrr')" != "true" ]; then
            apply_monitor "$desc" "$mode" "$scale" "$transform" "$current"
            show_message "Adaptive sync" \
                "$name ($(jq -r '"\(.make) \(.model)"' <<< "$m")) does not support adaptive sync"
            return
        fi
    fi
    change_monitor "$name" "$mode" "$scale" "$transform" "$i"
}

# ----------------------------------------------------------------------------
# Night light (hyprsunset)
# ----------------------------------------------------------------------------

# Saved temperature in kelvin, 0 when off
saved_nightlight() {
    jq -r '.nightlight // 0' "$GLOBAL_STATE"
}

nightlight_name() {
    if [ "$1" = "0" ]; then echo "Off"; else echo "$1 K"; fi
}

# hyprsunset only runs while the night light is on, so "off" means the colors
# are untouched; the gamma is restored when it exits
apply_nightlight() {
    local temp="$1"
    if [ "$temp" = "0" ]; then
        pkill -x hyprsunset
    elif pgrep -x hyprsunset > /dev/null; then
        hyprctl hyprsunset temperature "$temp" > /dev/null
    else
        hyprsunset --temperature "$temp" > /dev/null 2>&1 &
        disown
    fi
}

choose_nightlight() {
    if ! command -v hyprsunset > /dev/null; then
        show_message "Night light" "hyprsunset is not installed"
        return
    fi

    local current rows=("Off") values=(0) active=0 t
    current=$(saved_nightlight)
    for t in "${NIGHTLIGHT_TEMPS[@]}"; do
        values+=("$t")
        rows+=("$t K")
        [ "$t" = "$current" ] && active=$((${#values[@]} - 1))
    done

    local i
    i=$(rofi_menu "Night light" "$active" "${rows[@]}") || return
    apply_nightlight "${values[$i]}"

    local tmp
    tmp=$(mktemp)
    jq --argjson t "${values[$i]}" '.nightlight = $t' "$GLOBAL_STATE" > "$tmp" && mv "$tmp" "$GLOBAL_STATE"
    write_settings_lua
}

reset_monitor() {
    local name="$1" m desc
    m=$(monitor_json "$name")
    desc=$(jq -r '.description' <<< "$m")
    local i
    i=$(rofi_menu "Reset $name to defaults?" -1 "Reset" "Cancel") || return
    [ "$i" = "0" ] || return
    forget_monitor "$desc"
    hyprctl eval "hl.monitor({ output = $(jq -n --arg d "desc:$desc" '$d'), mode = \"preferred\", position = \"auto\", scale = 1 })" > /dev/null
}

display_menu() {
    local name="$1" m i
    while true; do
        m=$(monitor_json "$name")
        [ -n "$m" ] || return
        i=$(rofi_menu "Display $name" -1 \
            "$(row "Scale" "$(jq -r '.scale' <<< "$m")")" \
            "$(row "Resolution" "$(jq -r '"\(.width)x\(.height) @ \(.refreshRate * 100 | round / 100) Hz"' <<< "$m")")" \
            "$(row "Rotation" "$(transform_name "$(jq -r '.transform' <<< "$m")")")" \
            "$(row "Adaptive sync" "$(vrr_name "$(saved_vrr "$(jq -r '.description' <<< "$m")")")")" \
            "$(row "Night light" "$(nightlight_name "$(saved_nightlight)")")" \
            "Reset to defaults") || return
        case "$i" in
            0) choose_scale "$name" ;;
            1) choose_resolution "$name" ;;
            2) choose_rotation "$name" ;;
            3) choose_vrr "$name" ;;
            4) choose_nightlight ;;
            5) reset_monitor "$name" ;;
        esac
    done
}

choose_display() {
    local names=() rows=()
    mapfile -t names < <(hyprctl -j monitors | jq -r '.[].name')
    if [ "${#names[@]}" -eq 1 ]; then
        display_menu "${names[0]}"
        return
    fi
    mapfile -t rows < <(hyprctl -j monitors | jq -r '.[] | "\(.name)  \(.make) \(.model)"')
    local i
    while i=$(rofi_menu "Display" -1 "${rows[@]}"); do
        display_menu "${names[$i]}"
    done
}

# ----------------------------------------------------------------------------
# Appearance (hl.config options, applied live)
# ----------------------------------------------------------------------------

# Border colors: the Nordic Mist palette plus the default orange
COLOR_NAMES=(Orange Sage Teal Peach Lavender Sand Taupe Red Yellow Gray Dark)
COLOR_VALUES=(cc5500 9caf9f 6fa7a6 d7a58f b79ac8 cfc3b4 b8a89a c97f7f d6a65c 6b6460 2a2b30)

# Lua config key "general.gaps_in" -> getoption name "general:gaps_in";
# the "col." prefix is part of the option name and keeps its dot
option_name() {
    local key="${1//./:}"
    echo "${key/:col:/:col.}"
}

# Current value as JSON: number, true/false or "rgba(rrggbbaa)"
get_option() {
    hyprctl -j getoption "$(option_name "$1")" | jq -c '
        if has("css") then (.css | split(" ")[0] | tonumber)
        elif has("gradient") then (.gradient | split(" ")[0]
            | "rgba(" + .[2:] + .[0:2] + ")")
        elif has("float") then (.float * 1000 | round / 1000)
        elif has("int") then .int
        elif has("bool") then .bool
        else empty end'
}

# set_option <key> <json value>: apply live and remember it
set_option() {
    local lua tmp
    lua=$(jq -nr --arg k "$1" --argjson v "$2" '
        def lua: if type == "object"
            then "{ " + ([to_entries[] | "\(.key) = \(.value | lua)"] | join(", ")) + " }"
            elif type == "string" then tojson
            else tostring end;
        {} | setpath($k | split("."); $v) | "hl.config(\(lua))"')
    hyprctl eval "$lua" > /dev/null
    tmp=$(mktemp)
    jq --arg k "$1" --argjson v "$2" '.config[$k] = $v' "$GLOBAL_STATE" > "$tmp" && mv "$tmp" "$GLOBAL_STATE"
    write_settings_lua
}

on_off() {
    if [ "$1" = "true" ]; then echo "On"; else echo "Off"; fi
}

color_name() {
    local hex="${1#rgba(}" i
    hex="${hex:0:6}"
    for i in "${!COLOR_VALUES[@]}"; do
        [ "${COLOR_VALUES[$i]}" = "$hex" ] && { echo "${COLOR_NAMES[$i]}"; return; }
    done
    echo "#$hex"
}

# choose_number <key> <label> <values...>
choose_number() {
    local key="$1" label="$2" current active=-1 i v
    shift 2
    current=$(get_option "$key")
    for i in $(seq 0 $(($# - 1))); do
        v="${@:$((i + 1)):1}"
        awk -v a="$v" -v b="$current" 'BEGIN { exit !(a + 0 == b + 0) }' && active=$i
    done
    i=$(rofi_menu "$label" "$active" "$@") || return
    [ "$i" = "$active" ] && return
    v="${@:$((i + 1)):1}"
    set_option "$key" "$v"
}

choose_bool() {
    local key="$1" label="$2" current active
    current=$(get_option "$key")
    if [ "$current" = "true" ]; then active=0; else active=1; fi
    local i
    i=$(rofi_menu "$label" "$active" "On" "Off") || return
    [ "$i" = "$active" ] && return
    if [ "$i" = "0" ]; then set_option "$key" true; else set_option "$key" false; fi
}

choose_color() {
    local key="$1" label="$2" current active=-1 rows=() i
    current=$(get_option "$key" | jq -r '.')
    for i in "${!COLOR_NAMES[@]}"; do
        rows+=("$(row "${COLOR_NAMES[$i]}" \
            "<span foreground='#${COLOR_VALUES[$i]}'>■■</span>  #${COLOR_VALUES[$i]}")")
        [ "rgba(${COLOR_VALUES[$i]}ff)" = "$current" ] && active=$i
    done
    i=$(ROFI_MARKUP=1 rofi_menu "$label" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    set_option "$key" "\"rgba(${COLOR_VALUES[$i]}ff)\""
}

# Dim inactive windows: off, or on with a strength
choose_dim() {
    local enabled strength active=0 values=(0.1 0.2 0.3 0.4 0.5) rows=("Off") i v
    enabled=$(get_option decoration.dim_inactive)
    strength=$(get_option decoration.dim_strength)
    for i in "${!values[@]}"; do
        rows+=("${values[$i]}")
        [ "$enabled" = "true" ] && awk -v a="${values[$i]}" -v b="$strength" \
            'BEGIN { exit !(a + 0 == b + 0) }' && active=$((i + 1))
    done
    i=$(rofi_menu "Dim inactive windows" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    if [ "$i" = "0" ]; then
        set_option decoration.dim_inactive false
    else
        set_option decoration.dim_strength "${values[$((i - 1))]}"
        set_option decoration.dim_inactive true
    fi
}

dim_value() {
    if [ "$(get_option decoration.dim_inactive)" = "true" ]; then
        get_option decoration.dim_strength
    else
        echo "Off"
    fi
}

# Window open/close animation style; keeps the speed and curve of each leaf
WINDOW_STYLES=("popin" "slide" "gnomed")
WINDOW_STYLE_NAMES=("Pop in" "Slide" "Gnomed")

window_style() {
    hyprctl -j animations | jq -r '.[0][] | select(.name == "windows") | .style | split(" ")[0]'
}

window_style_name() {
    local style i
    style=$(window_style)
    for i in "${!WINDOW_STYLES[@]}"; do
        [ "${WINDOW_STYLES[$i]}" = "$style" ] && { echo "${WINDOW_STYLE_NAMES[$i]}"; return; }
    done
    echo "$style"
}

choose_window_style() {
    local current active=-1 i
    current=$(window_style)
    for i in "${!WINDOW_STYLES[@]}"; do
        [ "${WINDOW_STYLES[$i]}" = "$current" ] && active=$i
    done
    i=$(rofi_menu "Window animation" "$active" "${WINDOW_STYLE_NAMES[@]}") || return
    [ "$i" = "$active" ] && return

    local style="${WINDOW_STYLES[$i]}" leaf leaf_style anims tmp
    anims=$(hyprctl -j animations)
    for leaf in windows windowsOut; do
        # Closing windows shrink to 80% instead of to nothing
        leaf_style="$style"
        [ "$leaf" = "windowsOut" ] && [ "$style" = "popin" ] && leaf_style="popin 80%"
        tmp=$(mktemp)
        jq --arg leaf "$leaf" --arg style "$leaf_style" --argjson a "$anims" '
            ($a[0][] | select(.name == $leaf)) as $cur
            | .animations[$leaf] = { speed: $cur.speed, bezier: $cur.bezier, style: $style }
        ' "$GLOBAL_STATE" > "$tmp" && mv "$tmp" "$GLOBAL_STATE"
        hyprctl eval "$(jq -r --arg leaf "$leaf" '.animations[$leaf] as $v
            | "hl.animation({ leaf = \($leaf | tojson), enabled = true, speed = \($v.speed),"
              + " bezier = \($v.bezier | tojson), style = \($v.style | tojson) })"' "$GLOBAL_STATE")" > /dev/null
    done
    write_settings_lua
}

reset_appearance() {
    local i tmp
    i=$(rofi_menu "Reset appearance to defaults?" -1 "Reset" "Cancel") || return
    [ "$i" = "0" ] || return
    tmp=$(mktemp)
    jq 'del(.config, .animations)' "$GLOBAL_STATE" > "$tmp" && mv "$tmp" "$GLOBAL_STATE"
    write_settings_lua
    # Reload so the values from the Ansible-managed config apply again
    hyprctl reload > /dev/null
}

appearance_menu() {
    local i
    while true; do
        i=$(rofi_menu "Appearance" -1 \
            "$(row "Gaps inside" "$(get_option general.gaps_in)")" \
            "$(row "Gaps outside" "$(get_option general.gaps_out)")" \
            "$(row "Border size" "$(get_option general.border_size)")" \
            "$(row "Active border" "$(color_name "$(get_option general.col.active_border | jq -r .)")")" \
            "$(row "Inactive border" "$(color_name "$(get_option general.col.inactive_border | jq -r .)")")" \
            "$(row "Rounding" "$(get_option decoration.rounding)")" \
            "$(row "Active opacity" "$(get_option decoration.active_opacity)")" \
            "$(row "Inactive opacity" "$(get_option decoration.inactive_opacity)")" \
            "$(row "Dim inactive" "$(dim_value)")" \
            "$(row "Blur" "$(on_off "$(get_option decoration.blur.enabled)")")" \
            "$(row "Blur size" "$(get_option decoration.blur.size)")" \
            "$(row "Blur passes" "$(get_option decoration.blur.passes)")" \
            "$(row "Shadows" "$(on_off "$(get_option decoration.shadow.enabled)")")" \
            "$(row "Shadow range" "$(get_option decoration.shadow.range)")" \
            "$(row "Animations" "$(on_off "$(get_option animations.enabled)")")" \
            "$(row "Window animation" "$(window_style_name)")" \
            "$(row "Wallpaper" "Alt+W")" \
            "Reset to defaults") || return
        case "$i" in
            0) choose_number general.gaps_in "Gaps inside" 0 2 4 6 8 10 12 16 20 ;;
            1) choose_number general.gaps_out "Gaps outside" 0 4 8 12 16 20 24 32 ;;
            2) choose_number general.border_size "Border size" 0 1 2 3 4 ;;
            3) choose_color general.col.active_border "Active border" ;;
            4) choose_color general.col.inactive_border "Inactive border" ;;
            5) choose_number decoration.rounding "Rounding" 0 2 4 5 6 8 10 12 16 20 ;;
            6) choose_number decoration.active_opacity "Active opacity" 1 0.95 0.9 0.85 0.8 ;;
            7) choose_number decoration.inactive_opacity "Inactive opacity" 1 0.95 0.9 0.85 0.8 0.75 0.7 ;;
            8) choose_dim ;;
            9) choose_bool decoration.blur.enabled "Blur" ;;
            10) choose_number decoration.blur.size "Blur size" 1 2 3 4 5 6 8 10 ;;
            11) choose_number decoration.blur.passes "Blur passes" 1 2 3 4 ;;
            12) choose_bool decoration.shadow.enabled "Shadows" ;;
            13) choose_number decoration.shadow.range "Shadow range" 2 4 8 12 16 20 30 ;;
            14) choose_bool animations.enabled "Animations" ;;
            15) choose_window_style ;;
            16) "$HOME/.config/hypr/scripts/wallpaper-grid.sh"; return ;;
            17) reset_appearance ;;
        esac
    done
}

# ----------------------------------------------------------------------------
# Power and idle (hypridle, power-profiles-daemon)
# ----------------------------------------------------------------------------

# Timeouts in seconds, 0 = never. The defaults match hypr/hypridle.conf.
IDLE_KEYS=(dim lock screen_off suspend)
IDLE_LABELS=("Dim screen" "Lock screen" "Screen off" "Suspend")
IDLE_DEFAULTS=(150 300 330 3600)
IDLE_CHOICES_dim=(0 60 150 300 600)
IDLE_CHOICES_lock=(0 300 600 900 1800 3600)
IDLE_CHOICES_screen_off=(0 300 600 900 1800 3600)
IDLE_CHOICES_suspend=(0 900 1800 3600 7200)

# saved_idle <index into IDLE_KEYS>
saved_idle() {
    jq -r --arg k "${IDLE_KEYS[$1]}" --argjson d "${IDLE_DEFAULTS[$1]}" \
        '.idle[$k] // $d' "$GLOBAL_STATE"
}

duration_name() {
    awk -v s="$1" 'BEGIN {
        if (s == 0) print "Never"
        else if (s < 60) printf "%d s\n", s
        else if (s < 3600) printf "%g min\n", s / 60
        else printf "%g h\n", s / 3600
    }'
}

write_idle_conf() {
    local dim lock screen_off suspend
    dim=$(saved_idle 0)
    lock=$(saved_idle 1)
    screen_off=$(saved_idle 2)
    suspend=$(saved_idle 3)
    {
        echo "# Generated by ~/.config/hypr/scripts/settings.sh (Alt+Shift+S)."
        echo "# Do not edit by hand; use the settings menu or delete this file."
        cat << 'EOF2'
general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
EOF2
        [ "$dim" != "0" ] && printf '\nlistener {\n    timeout = %s\n    on-timeout = brightnessctl -s set 10\n    on-resume = brightnessctl -r\n}\n' "$dim"
        [ "$lock" != "0" ] && printf '\nlistener {\n    timeout = %s\n    on-timeout = loginctl lock-session\n}\n' "$lock"
        [ "$screen_off" != "0" ] && printf '\nlistener {\n    timeout = %s\n    on-timeout = hyprctl dispatch %s\n    on-resume = hyprctl dispatch %s\n}\n' \
            "$screen_off" "'hl.dsp.dpms({ action = \"disable\" })'" "'hl.dsp.dpms({ action = \"enable\" })'"
        [ "$suspend" != "0" ] && printf '\nlistener {\n    timeout = %s\n    on-timeout = systemctl suspend\n}\n' "$suspend"
    } > "$IDLE_CONF"
}

# hypridle does not reload its config, so restart it
restart_hypridle() {
    pkill -x hypridle
    setsid -f "$HOME/.config/hypr/scripts/hypridle.sh" > /dev/null 2>&1
}

# choose_idle <index into IDLE_KEYS>
choose_idle() {
    local idx="$1" key="${IDLE_KEYS[$1]}" current active=-1 rows=() i v
    local -n choices="IDLE_CHOICES_$key"
    current=$(saved_idle "$idx")
    for i in "${!choices[@]}"; do
        rows+=("$(duration_name "${choices[$i]}")")
        [ "${choices[$i]}" = "$current" ] && active=$i
    done
    i=$(rofi_menu "${IDLE_LABELS[$idx]}" "$active" "${rows[@]}") || return
    [ "$i" = "$active" ] && return
    v="${choices[$i]}"

    local tmp
    tmp=$(mktemp)
    jq --arg k "$key" --argjson v "$v" '.idle[$k] = $v' "$GLOBAL_STATE" > "$tmp" && mv "$tmp" "$GLOBAL_STATE"
    write_idle_conf
    restart_hypridle
}

# Power profiles are kept by power-profiles-daemon itself, so nothing is saved
choose_power_profile() {
    if ! command -v powerprofilesctl > /dev/null; then
        show_message "Power profile" "power-profiles-daemon is not installed"
        return
    fi
    local profiles=() current active=-1 i
    mapfile -t profiles < <(powerprofilesctl list | sed -n 's/^[* ] \(.*\):$/\1/p')
    current=$(powerprofilesctl get)
    for i in "${!profiles[@]}"; do
        [ "${profiles[$i]}" = "$current" ] && active=$i
    done
    i=$(rofi_menu "Power profile" "$active" "${profiles[@]}") || return
    [ "$i" = "$active" ] && return
    powerprofilesctl set "${profiles[$i]}"
}

reset_power() {
    local i tmp
    i=$(rofi_menu "Reset power and idle to defaults?" -1 "Reset" "Cancel") || return
    [ "$i" = "0" ] || return
    tmp=$(mktemp)
    jq 'del(.idle)' "$GLOBAL_STATE" > "$tmp" && mv "$tmp" "$GLOBAL_STATE"
    rm -f "$IDLE_CONF"
    restart_hypridle
}

power_menu() {
    local i idx rows
    while true; do
        rows=()
        for idx in "${!IDLE_KEYS[@]}"; do
            rows+=("$(row "${IDLE_LABELS[$idx]}" "$(duration_name "$(saved_idle "$idx")")")")
        done
        rows+=("$(row "Power profile" "$(powerprofilesctl get 2> /dev/null || echo "-")")")
        rows+=("Reset to defaults")
        i=$(rofi_menu "Power and idle" -1 "${rows[@]}") || return
        case "$i" in
            0 | 1 | 2 | 3) choose_idle "$i" ;;
            4) choose_power_profile ;;
            5) reset_power ;;
        esac
    done
}

# ----------------------------------------------------------------------------
# Main menu
# ----------------------------------------------------------------------------

main_menu() {
    local i
    while i=$(rofi_menu "Settings" -1 "󰍹  Display" "󰏘  Appearance" "󰐥  Power and idle"); do
        case "$i" in
            0) choose_display ;;
            1) appearance_menu ;;
            2) power_menu ;;
        esac
    done
}

# Only open the menu when run directly, so the functions can be sourced
[[ ${BASH_SOURCE[0]} == "$0" ]] && main_menu
